FROM node:14.3.0-stretch-slim

# Create app directory
WORKDIR /usr/src/app/graphql-server

# Copy generated code into the skeleton GraphQL-Server
COPY . .

# Clone the skeleton project and install dependencies
RUN apt-get update && apt-get install -y autoconf libtool make && \	
  rm -rf .git* && \
  chmod u+x ./migrateDbAndStartServer.sh && \
  npm install 

EXPOSE 3000
