module.exports = {
  LIMIT_RECORDS : process.env.LIMIT_RECORDS || 10000,
  PORT : process.env.PORT || 3000,
  ALLOW_ORIGIN: process.env.ALLOW_ORIGIN || "http://localhost:8080",
  JWT_SECRET: process.env.JWT_SECRET || "something-secret",
  SALT_ROUNDS: process.env.SALT_ROUNDS || 10,
  REQUIRE_SIGN_IN: process.env.REQUIRE_SIGN_IN || "true",
  MAX_TIME_OUT: process.env.MAX_TIME_OUT || 2000,
  POST_REQUEST_MAX_BODY_SIZE: process.env.POST_REQUEST_MAX_BODY_SIZE || '1mb',
  ERROR_LOG: process.env.ERROR_LOG || 'compact',
  MAIL_SERVICE: process.env.MAIL_SERVICE || "gmail",
  MAIL_HOST: process.env.MAIL_HOST || "smtp.gmail.com",
  MAIL_ACCOUNT: process.env.MAIL_ACCOUNT || "sci.db.service@gmail.com",
  MAIL_PASSWORD: process.env.MAIL_PASSWORD || "SciDbServiceQAZ",
  EXPORT_TIME_OUT: process.env.EXPORT_TIME_OUT || 3600,
  // image attachment configs:
  SMALL_THUMBNAIL_SIZE: process.env.SMALL_THUMBNAIL_SIZE || "64x64",
  MEDIUM_THUMBNAIL_SIZE: process.env.MEDIUM_THUMBNAIL_SIZE || "120x120",
  PUBLIC_FOLDER: process.env.PUBLIC_FOLDER || "public",
  IMAGE_HOST_SERVER_BASE_URL: process.env.IMAGE_HOST_SERVER_BASE_URL || "http://localhost:3000/",
  MAX_FILES_PER_ATTACHMENT_FOLDER: process.env.MAX_FILES_PER_ATTACHMENT_FOLDER || 50000,
  PUBLIC_ATTACHMENT_FOLDER_DEPTH: process.env.PUBLIC_ATTACHMENT_FOLDER_DEPTH || 2,
  CREATE_IMAGE_ATTACHMENT_FILE_REQUIRED: process.env.CREATE_IMAGE_ATTACHMENT_FILE_REQUIRED || true,
}
