
export default () => ({
  models: [
    {
      id: 0,
      name: 'breedingMethod',
      title: 'BreedingMethod',
      url: '/main/model/breedingMethod',
    },
    {
      id: 1,
      name: 'contact',
      title: 'Contact',
      url: '/main/model/contact',
    },
    {
      id: 2,
      name: 'environmentParameter',
      title: 'EnvironmentParameter',
      url: '/main/model/environmentParameter',
    },
    {
      id: 3,
      name: 'event',
      title: 'Event',
      url: '/main/model/event',
    },
    {
      id: 4,
      name: 'eventParameter',
      title: 'EventParameter',
      url: '/main/model/eventParameter',
    },
    {
      id: 5,
      name: 'germplasm',
      title: 'Germplasm',
      url: '/main/model/germplasm',
    },
    {
      id: 6,
      name: 'image',
      title: 'Image',
      url: '/main/model/image',
    },
    {
      id: 7,
      name: 'location',
      title: 'Location',
      url: '/main/model/location',
    },
    {
      id: 8,
      name: 'method',
      title: 'Method',
      url: '/main/model/method',
    },
    {
      id: 9,
      name: 'observation',
      title: 'Observation',
      url: '/main/model/observation',
    },
    {
      id: 10,
      name: 'observationTreatment',
      title: 'ObservationTreatment',
      url: '/main/model/observationTreatment',
    },
    {
      id: 11,
      name: 'observationUnit',
      title: 'ObservationUnit',
      url: '/main/model/observationUnit',
    },
    {
      id: 12,
      name: 'observationUnitPosition',
      title: 'ObservationUnitPosition',
      url: '/main/model/observationUnitPosition',
    },
    {
      id: 13,
      name: 'observationUnit_to_event',
      title: 'ObservationUnit_to_event',
      url: '/main/model/observationUnit_to_event',
    },
    {
      id: 14,
      name: 'observationVariable',
      title: 'ObservationVariable',
      url: '/main/model/observationVariable',
    },
    {
      id: 15,
      name: 'ontologyReference',
      title: 'OntologyReference',
      url: '/main/model/ontologyReference',
    },
    {
      id: 16,
      name: 'program',
      title: 'Program',
      url: '/main/model/program',
    },
    {
      id: 17,
      name: 'role_to_user',
      title: 'Role_to_user',
      url: '/main/model/role_to_user',
    },
    {
      id: 18,
      name: 'scale',
      title: 'Scale',
      url: '/main/model/scale',
    },
    {
      id: 19,
      name: 'season',
      title: 'Season',
      url: '/main/model/season',
    },
    {
      id: 20,
      name: 'study',
      title: 'Study',
      url: '/main/model/study',
    },
    {
      id: 21,
      name: 'study_to_contact',
      title: 'Study_to_contact',
      url: '/main/model/study_to_contact',
    },
    {
      id: 22,
      name: 'study_to_season',
      title: 'Study_to_season',
      url: '/main/model/study_to_season',
    },
    {
      id: 23,
      name: 'trait',
      title: 'Trait',
      url: '/main/model/trait',
    },
    {
      id: 24,
      name: 'trial',
      title: 'Trial',
      url: '/main/model/trial',
    },
    {
      id: 25,
      name: 'trial_to_contact',
      title: 'Trial_to_contact',
      url: '/main/model/trial_to_contact',
    },
  ],
  adminModels: [
    {
      id: 26,
      name: 'role',
      title: 'Role',
      url: '/main/admin/role',
    },
    {
      id: 27,
      name: 'user',
      title: 'User',
      url: '/main/admin/user',
    },
  ]
})