FROM node:11.12.0-alpine

RUN apk update && \
 apk add git && apk add bash && \
 npm install -g github:ScienceDb/graphql-server-model-codegen.git#alpha-0.1.0-merge && \
 npm install -g github:ScienceDb/single-page-app-codegen.git#alpha-0.1.0-merge

ENTRYPOINT ["/bin/bash"]
